"""empty message

Revision ID: 2a914a1c6550
Revises: 50dca22516b5
Create Date: 2016-08-18 13:39:26.837841

"""

# revision identifiers, used by Alembic.
revision = '2a914a1c6550'
down_revision = '50dca22516b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'created_date')
    ### end Alembic commands ###
