"""empty message

Revision ID: 3372c222af79
Revises: 5ab20e75b01b
Create Date: 2016-10-27 00:25:31.506317

"""

# revision identifiers, used by Alembic.
revision = '3372c222af79'
down_revision = '5ab20e75b01b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
