"""empty message

Revision ID: 4abe06c229ee
Revises: None
Create Date: 2016-08-08 20:38:20.163230

"""

# revision identifiers, used by Alembic.
revision = '4abe06c229ee'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'posts', sa.Column('category_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'posts', 'category_id')
    op.drop_table('categories')
    ### end Alembic commands ###
