"""empty message

Revision ID: 55d309f2ea4
Revises: aa41cb73f0
Create Date: 2016-09-14 18:52:26.094525

"""

# revision identifiers, used by Alembic.
revision = '55d309f2ea4'
down_revision = 'aa41cb73f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('private_favorites', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'private_favorites')
    ### end Alembic commands ###
