"""empty message

Revision ID: 56d96a557fb1
Revises: 4abe06c229ee
Create Date: 2016-08-09 20:11:16.994139

"""

# revision identifiers, used by Alembic.
revision = '56d96a557fb1'
down_revision = '4abe06c229ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
