"""empty message

Revision ID: 5ab20e75b01b
Revises: 31e476d557d9
Create Date: 2016-10-25 22:21:13.573134

"""

# revision identifiers, used by Alembic.
revision = '5ab20e75b01b'
down_revision = '31e476d557d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
