"""empty message

Revision ID: aa41cb73f0
Revises: cc163b25224
Create Date: 2016-09-09 19:20:56.488980

"""

# revision identifiers, used by Alembic.
revision = 'aa41cb73f0'
down_revision = 'cc163b25224'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
