"""empty message

Revision ID: cc163b25224
Revises: 294e8351547f
Create Date: 2016-08-30 17:15:26.571807

"""

# revision identifiers, used by Alembic.
revision = 'cc163b25224'
down_revision = '294e8351547f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favs',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favs')
    ### end Alembic commands ###
